# Generated by Django 4.2 on 2023-07-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurrence', '0002_alter_date_id_alter_param_id_alter_recurrence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='param',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
